List<Map<String, dynamic>> surahs = [
  {
    'nameArabic': 'الفاتحة',
    'numberOfAyahs': 7,
    'type': 'مكية',
  },
  {'nameArabic': 'البقرة', 'numberOfAyahs': 286, 'type': 'مدنية'},
  {'nameArabic': 'آل عمران', 'numberOfAyahs': 200, 'type': 'مدنية'},
  {'nameArabic': 'النساء', 'numberOfAyahs': 176, 'type': 'مدنية'},
  {'nameArabic': 'المائدة', 'numberOfAyahs': 120, 'type': 'مدنية'},
  {'nameArabic': 'الأنعام', 'numberOfAyahs': 165, 'type': 'مكية'},
  {'nameArabic': 'الأعراف', 'numberOfAyahs': 206, 'type': 'مكية'},
  {'nameArabic': 'الأنفال', 'numberOfAyahs': 75, 'type': 'مدنية'},
  {'nameArabic': 'التوبة', 'numberOfAyahs': 129, 'type': 'مدنية'},
  {'nameArabic': 'يونس', 'numberOfAyahs': 109, 'type': 'مكية'},
  {'nameArabic': 'هود', 'numberOfAyahs': 123, 'type': 'مكية'},
  {'nameArabic': 'يوسف', 'numberOfAyahs': 111, 'type': 'مكية'},
  {'nameArabic': 'الرعد', 'numberOfAyahs': 43, 'type': 'مكية'},
  {'nameArabic': 'إبراهيم', 'numberOfAyahs': 52, 'type': 'مكية'},
  {'nameArabic': 'الحجر', 'numberOfAyahs': 99, 'type': 'مكية'},
  {'nameArabic': 'النحل', 'numberOfAyahs': 128, 'type': 'مكية'},
  {'nameArabic': 'الإسراء', 'numberOfAyahs': 111, 'type': 'مكية'},
  {'nameArabic': 'الكهف', 'numberOfAyahs': 110, 'type': 'مكية'},
  {'nameArabic': 'مريم', 'numberOfAyahs': 98, 'type': 'مكية'},
  {'nameArabic': 'طه', 'numberOfAyahs': 135, 'type': 'مكية'},
  {'nameArabic': 'الأنبياء', 'numberOfAyahs': 112, 'type': 'مكية'},
  {'nameArabic': 'الحج', 'numberOfAyahs': 78, 'type': 'مدنية'},
  {'nameArabic': 'المؤمنون', 'numberOfAyahs': 118, 'type': 'مكية'},
  {'nameArabic': 'النور', 'numberOfAyahs': 64, 'type': 'مدنية'},
  {'nameArabic': 'الفرقان', 'numberOfAyahs': 77, 'type': 'مكية'},
  {'nameArabic': 'الشعراء', 'numberOfAyahs': 227, 'type': 'مكية'},
  {'nameArabic': 'النمل', 'numberOfAyahs': 93, 'type': 'مكية'},
  {
    'nameArabic': 'القصص',
    'numberOfAyahs': 88,
    'type': 'مكية',
  },
  {'nameArabic': 'العنكبوت', 'numberOfAyahs': 69, 'type': 'مكية'},
  {'nameArabic': 'الروم', 'numberOfAyahs': 60, 'type': 'مكية'},
  {'nameArabic': 'لقمان', 'numberOfAyahs': 34, 'type': 'مكية'},
  {'nameArabic': 'السجدة', 'numberOfAyahs': 30, 'type': 'مكية'},
  {'nameArabic': 'الأحزاب', 'numberOfAyahs': 73, 'type': 'مدنية'},
  {
    'nameArabic': 'سبأ',
    'numberOfAyahs': 54,
    'type': 'مكية ',
  },
  {
    'nameArabic': 'فاطر',
    'numberOfAyahs': 45,
    'type': 'مكية ',
  },
  {'nameArabic': 'يس', 'numberOfAyahs': 83, 'type': 'مكية'},
  {'nameArabic': 'الصافات', 'numberOfAyahs': 182, 'type': 'مكية'},
  {'nameArabic': 'ص', 'numberOfAyahs': 88, 'type': 'مكية'},
  {'nameArabic': 'الزمر', 'numberOfAyahs': 75, 'type': 'مكية'},
  {'nameArabic': 'غافر', 'numberOfAyahs': 85, 'type': 'مكية'},
  {'nameArabic': 'فصلت', 'numberOfAyahs': 54, 'type': 'مكية'},
  {'nameArabic': 'الشورى', 'numberOfAyahs': 53, 'type': 'مكية'},
  {'nameArabic': 'الزخرف', 'numberOfAyahs': 89, 'type': 'مكية'},
  {'nameArabic': 'الدخان', 'numberOfAyahs': 59, 'type': 'مكية'},
  {'nameArabic': 'الجاثية', 'numberOfAyahs': 37, 'type': 'مكية'},
  {'nameArabic': 'الأحقاف', 'numberOfAyahs': 35, 'type': 'مكية'},
  {'nameArabic': 'محمد', 'numberOfAyahs': 38, 'type': 'مدنية'},
  {'nameArabic': 'الفتح', 'numberOfAyahs': 29, 'type': 'مدنية'},
  {'nameArabic': 'الحجرات', 'numberOfAyahs': 18, 'type': 'مدنية'},
  {'nameArabic': 'ق', 'numberOfAyahs': 45, 'type': 'مكية'},
  {'nameArabic': 'الذاريات', 'numberOfAyahs': 60, 'type': 'مكية'},
  {'nameArabic': 'الطور', 'numberOfAyahs': 49, 'type': 'مكية'},
  {'nameArabic': 'النجم', 'numberOfAyahs': 62, 'type': 'مكية'},
  {'nameArabic': 'القمر', 'numberOfAyahs': 55, 'type': 'مكية'},
  {'nameArabic': 'الرحمن', 'numberOfAyahs': 78, 'type': 'مدنية'},
  {'nameArabic': 'الواقعة', 'numberOfAyahs': 96, 'type': 'مكية'},
  {'nameArabic': 'الحديد', 'numberOfAyahs': 29, 'type': 'مدنية'},
  {'nameArabic': 'المجادلة', 'numberOfAyahs': 22, 'type': 'مدنية'},
  {'nameArabic': 'الحشر', 'numberOfAyahs': 24, 'type': 'مدنية'},
  {'nameArabic': 'الممتحنة', 'numberOfAyahs': 13, 'type': 'مدنية'},
  {'nameArabic': 'الصف', 'numberOfAyahs': 14, 'type': 'مدنية'},
  {'nameArabic': 'الجمعة', 'numberOfAyahs': 11, 'type': 'مدنية'},
  {'nameArabic': 'المنافقون', 'numberOfAyahs': 11, 'type': 'مدنية'},
  {'nameArabic': 'التغابن', 'numberOfAyahs': 18, 'type': 'مدنية'},
  {'nameArabic': 'الطلاق', 'numberOfAyahs': 12, 'type': 'مدنية'},
  {'nameArabic': 'التحريم', 'numberOfAyahs': 12, 'type': 'مدنية'},
  {'nameArabic': 'الملك', 'numberOfAyahs': 30, 'type': 'مكية'},
  {'nameArabic': 'القلم', 'numberOfAyahs': 52, 'type': 'مكية'},
  {'nameArabic': 'الحاقة', 'numberOfAyahs': 29, 'type': 'مكية'},
  {'nameArabic': 'المعارج', 'numberOfAyahs': 44, 'type': 'مكية'},
  {'nameArabic': 'نوح', 'numberOfAyahs': 28, 'type': 'مكية'},
  {'nameArabic': 'الجن', 'numberOfAyahs': 28, 'type': 'مكية'},
  {'nameArabic': 'المزمل', 'numberOfAyahs': 20, 'type': 'مكية'},
  {'nameArabic': 'المدثر', 'numberOfAyahs': 56, 'type': 'مكية'},
  {'nameArabic': 'القيامة', 'numberOfAyahs': 40, 'type': 'مكية'},
  {'nameArabic': 'الإنسان', 'numberOfAyahs': 31, 'type': 'مدنية'},
  {'nameArabic': 'المرسلات', 'numberOfAyahs': 50, 'type': 'مكية'},
  {'nameArabic': 'النبأ', 'numberOfAyahs': 40, 'type': 'مكية'},
  {'nameArabic': 'النازعات', 'numberOfAyahs': 46, 'type': 'مكية'},
  {'nameArabic': 'عبس', 'numberOfAyahs': 42, 'type': 'مكية'},
  {'nameArabic': 'التكوير', 'numberOfAyahs': 29, 'type': 'مكية'},
  {'nameArabic': 'الإنفطار', 'numberOfAyahs': 19, 'type': 'مكية'},
  {'nameArabic': 'المطففين', 'numberOfAyahs': 36, 'type': 'مكية'},
  {'nameArabic': 'الانشقاق', 'numberOfAyahs': 25, 'type': 'مكية'},
  {'nameArabic': 'البروج', 'numberOfAyahs': 22, 'type': 'مكية'},
  {'nameArabic': 'الطارق', 'numberOfAyahs': 17, 'type': 'مكية'},
  {'nameArabic': 'الأعلى', 'numberOfAyahs': 19, 'type': 'مكية'},
  {'nameArabic': 'الغاشية', 'numberOfAyahs': 26, 'type': 'مكية'},
  {'nameArabic': 'الفجر', 'numberOfAyahs': 30, 'type': 'مكية'},
  {'nameArabic': 'البلد', 'numberOfAyahs': 20, 'type': 'مكية'},
  {'nameArabic': 'الشمس', 'numberOfAyahs': 15, 'type': 'مكية'},
  {'nameArabic': 'الليل', 'numberOfAyahs': 21, 'type': 'مكية'},
  {'nameArabic': 'الضحى', 'numberOfAyahs': 11, 'type': 'مكية'},
  {'nameArabic': 'الشرح', 'numberOfAyahs': 8, 'type': 'مكية'},
  {'nameArabic': 'التين', 'numberOfAyahs': 8, 'type': 'مكية'},
  {
    'nameArabic': 'العلق',
    'numberOfAyahs': 19,
    'type': 'مكية',
  },
  {'nameArabic': 'القدر', 'numberOfAyahs': 5, 'type': 'مكية'},
  {'nameArabic': 'البينة', 'numberOfAyahs': 8, 'type': 'مدنية'},
  {'nameArabic': 'الزلزلة', 'numberOfAyahs': 8, 'type': 'مدنية'},
  {'nameArabic': 'العاديات', 'numberOfAyahs': 11, 'type': 'مكية'},
  {'nameArabic': 'القارعة', 'numberOfAyahs': 11, 'type': 'مكية'},
  {'nameArabic': 'التكاثر', 'numberOfAyahs': 8, 'type': 'مكية'},
  {
    'nameArabic': 'العصر',
    'numberOfAyahs': 3,
    'type': 'مكية',
  },
  {
    'nameArabic': 'الهمزة',
    'numberOfAyahs': 9,
    'type': 'مكية',
  },
  {
    'nameArabic': 'الفيل',
    'numberOfAyahs': 5,
    'type': 'مكية',
  },
  {
    'nameArabic': 'قريش',
    'numberOfAyahs': 4,
    'type': 'مكية',
  },
  {
    'nameArabic': 'الماعون',
    'numberOfAyahs': 7,
    'type': 'مكية',
  },
  {
    'nameArabic': 'الكوثر',
    'numberOfAyahs': 3,
    'type': 'مكية',
  },
  {'nameArabic': 'الكافرون', 'numberOfAyahs': 6, 'type': 'مكية'},
  {'nameArabic': 'النصر', 'numberOfAyahs': 3, 'type': 'مدنية'},
  {'nameArabic': 'المسد', 'numberOfAyahs': 5, 'type': 'مكية'},
  {'nameArabic': 'الإخلاص', 'numberOfAyahs': 4, 'type': 'مكية'},
  {'nameArabic': 'الفلق', 'numberOfAyahs': 5, 'type': 'مكية'},
  {'nameArabic': 'الناس', 'numberOfAyahs': 6, 'type': 'مكية'},
];
