// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcT1telHb5cUWr99sGToopcbEF3tXJfHE',
    appId: '1:983976699627:web:6a6669bc3b2ba574ef00ae',
    messagingSenderId: '983976699627',
    projectId: 'quran-app-5a53c',
    authDomain: 'quran-app-5a53c.firebaseapp.com',
    storageBucket: 'quran-app-5a53c.appspot.com',
    measurementId: 'G-0XCZHLVTKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmVQgJ4_1d8vvHFFd0Cf4blPnnok1_0kQ',
    appId: '1:983976699627:android:8c711be83a742f39ef00ae',
    messagingSenderId: '983976699627',
    projectId: 'quran-app-5a53c',
    storageBucket: 'quran-app-5a53c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCES6FvDqefQXIJSlcq7gAmEaak2b8rTBY',
    appId: '1:983976699627:ios:0509dca1009f71efef00ae',
    messagingSenderId: '983976699627',
    projectId: 'quran-app-5a53c',
    storageBucket: 'quran-app-5a53c.appspot.com',
    iosBundleId: 'com.rehana.mo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCES6FvDqefQXIJSlcq7gAmEaak2b8rTBY',
    appId: '1:983976699627:ios:0509dca1009f71efef00ae',
    messagingSenderId: '983976699627',
    projectId: 'quran-app-5a53c',
    storageBucket: 'quran-app-5a53c.appspot.com',
    iosBundleId: 'com.rehana.mo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcT1telHb5cUWr99sGToopcbEF3tXJfHE',
    appId: '1:983976699627:web:8c28ce9defb0115bef00ae',
    messagingSenderId: '983976699627',
    projectId: 'quran-app-5a53c',
    authDomain: 'quran-app-5a53c.firebaseapp.com',
    storageBucket: 'quran-app-5a53c.appspot.com',
    measurementId: 'G-6SV6KB2HCV',
  );

}